
Guns = {
    "weapon_pwb_l85a1",
    "weapon_pwb_akm",
    "qwb_glock18",
    "weapon_pwb2_vectorsmg",
    "qwb_awp",
    "qwb_m3super",
    "weapon_pwb_aks74u",
    "weapon_pwb_m590a1",
    "weapon_pwb_cz75",
    "weapon_sib_usp",
    "weapon_pwb_p99",
    "weapon_pwb_desert_eagle",
    "weapon_pwb_fnp45",
    "weapon_pwb_glock17",
    "weapon_pwb_hk23e",
    "weapon_pwb_hk416",
    "weapon_pwb_m249",
    "weapon_pwb_m320",
    "weapon_pwb_m9",
    "weapon_pwb_remington_870",
    "weapon_sib_beretta",
    "weapon_sib_glock",
    "weapon_pwb_tar21",
    "weapon_pwb_protecta",
    "weapon_pwb_l96a1",
    "weapon_pwb_m200",
    "weapon_pwb_hk417",
    "weapon_pwb_mp7",
    "weapon_pwb_m98b",
    "weapon_pwb_m134",
    "weapon_pwb_mp5",
    "weapon_pwb_xm1014",
    "weapon_pwb_saiga_12",
    "weapon_pwb_rpk",
    "weapon_sib_m14",
    "weapon_pwb_pkm",
    "weapon_pwb_uzi",
    "weapon_pwb_spas_12",
    "qwb_ump45",
    "qwb_usp",
    "weapon_pwb_tmp",
    "weapon_pwb_p90",
    "weapon_sib_m249",
    "weapon_sib_deagle",
    }
    GunsModel = {
    ['weapon_pwb_l85a1'] = "models/pwb/weapons/w_l85a1.mdl",
    ["weapon_pwb_akm"] = "models/pwb/weapons/w_akm.md",
    ["weapon_pwb_aks74u"] = 'models/pwb/weapons/w_aks74u.mdl',
    ["weapon_pwb_cz75"] = 'models/pwb/weapons/w_aks74u.mdl',
    ["weapon_pwb_desert_eagle"] = 'models/pwb/weapons/w_desert_eagle.mdl',
    ["weapon_pwb_fnp45"] = 'models/pwb/weapons/w_fnp45.mdl',
    ["weapon_pwb_glock17"] = '',
    ["weapon_pwb_hk23e"] = '',
    ["weapon_pwb_hk416"] = '',
    ["weapon_pwb_hk417"] = '',
    }
    
    ShootWait = {
    ["weapon_pwb_akm"] = 0.1,
    ["weapon_pwb_p99"] = 0.1,
    ["qwb_glock18"] = 0.1,
    ["weapon_pwb2_vectorsmg"] = 0.1,
    ["qwb_m3super"] = 0.3,
    ["weapon_sib_glock"] = 0.1,
    ["weapon_sib_beretta"] = 0.1,
    ["weapon_pwb_l85a1"] = 0.1,
    ["weapon_pwb_tar21"] = 0.1,
    ["weapon_pwb_aks74u"] = 0.1,
    ["weapon_pwb_cz75"] = 0.06,
    ["weapon_pwb_fnp45"] = 0.2,
    ["weapon_pwb_desert_eagle"] = 0.35,
    ["weapon_pwb_m320"] = 0.9,
    ["weapon_pwb_glock17"] = 0.08,
    ["qwb_awp"] = 0.2,
    ["weapon_sib_m249"] = 0.1,
    ["weapon_pwb_m590a1"] = 0.9,
    ["weapon_pwb_tmp"] =0.09,
    ["weapon_sib_deagle"] = 0.2,
    ["weapon_pwb_spas_12"] = 0.2,
    ["weapon_pwb_remington_870"] =0.9,
    ["weapon_pwb_l96a1"] = 0.6,
    ["weapon_pwb_hk23e"] = 0.1,
    ["weapon_pwb_m134"] = 0.1,
    ["weapon_pwb_saiga_12"] = 0.4,
    ["weapon_pwb_uzi"] = 0.08,
    ["weapon_pwb_hk416"] = 0.1,
    ["weapon_pwb_hk417"] = 0.4,
    ["qwb_ump45"] = 0.1,
    ["weapon_pwb_mp7"] = 0.07,
    ["weapon_pwb_m200"] = 1,
    ["weapon_pwb_m249"] = 0.1,
    ["qwb_usp"] = 0.1,
    ["weapon_pwb_m98b"] = 1,
    ["weapon_pwb_m9"] = 0.2,
    ["weapon_sib_m14"] = 0.2,
    ["weapon_pwb_xm1014"] = 0.1,
    ["weapon_pwb_protecta"] = 0.4,
    ["weapon_sib_usp"] = 0.08,
    ["weapon_pwb_mp5"] = 0.1,
    ["weapon_pwb_rpk"] = 0.1,
    ["weapon_pwb_p90"] = 0.08,
    ["weapon_pwb_pkm"] = 0.1,
    }
    
    ReloadTime = {
    ["weapon_pwb_l85a1"] = 2,
    ["weapon_pwb_p99"] = 1,
    ["weapon_pwb2_vectorsmg"] = 2,
    ["weapon_pwb_mp5"] = 1,
    ["qwb_glock18"] = 1,
    ["weapon_sib_beretta"] = 1,
    ["qwb_awp"] = 2,
    ["qwb_m3super"] = 2,
    ["weapon_pwb_akm"] = 2,
    ["weapon_sib_glock"] = 1,
    ["weapon_pwb_aks74u"] = 2,
    ["weapon_pwb_cz75"] = 2,
    ["weapon_pwb_desert_eagle"] = 3,
    ["weapon_pwb_m590a1"] = 3,
    ["weapon_pwb_tar21"] = 3,
    ["weapon_pwb_fnp45"] = 2,
    ["weapon_pwb_glock17"] = 2,
    ["weapon_pwb_l96a1"] = 4,
    ["weapon_pwb_m320"] = 3,
    ["weapon_pwb_m9"] = 1,
    ["weapon_pwb_hk23e"] = 5,
    ["weapon_sib_usp"] = 1,
    ["weapon_sib_m249"] = 2,
    ["weapon_pwb_protecta"] = 2,
    ["weapon_pwb_remington_870"] = 2,
    ["weapon_pwb_xm1014"] = 5,
    ["weapon_pwb_spas_12"] = 5,
    ["weapon_pwb_hk416"] = 2,
    ["weapon_pwb_m134"] = 6,
    ["weapon_pwb_saiga_12"] = 2,
    ["weapon_pwb_uzi"] = 1,
    ["weapon_pwb_m98b"] = 3,
    ["weapon_pwb_m249"] = 5,
    ["weapon_pwb_hk417"] = 3,
    ["weapon_sib_m14"] = 2,
    ["weapon_pwb_p90"] = 2,
    ["weapon_pwb_mp7"] = 2,
    ["weapon_pwb_rpk"] = 4,
    ["weapon_pwb_pkm"] = 4,
    ["weapon_pwb_tmp"] = 2,
    ["weapon_pwb_m200"] = 4,
    ["qwb_usp"] = 1,
    ["qwb_ump45"] = 1,
    ["weapon_sib_deagle"] = 2,
    }
    
    
    TwoHandedOrNo = {
    ["weapon_sib_deagle"] = true,
    ["weapon_pwb_l85a1"] = true,
    ["weapon_pwb2_vectorsmg"] = true,
    ["weapon_pwb_m98b"] = true,
    ["weapon_pwb_p90"] = true,
    ["qwb_awp"] = true,
    ["qwb_glock18"] = true,
    ["weapon_sib_glock"] = true,
    ["weapon_sib_beretta"] = false ,
    ["weapon_pwb_akm"] = true,
    ["weapon_sib_usp"] = true,
    ["weapon_pwb_aks74u"] = true,
    ["weapon_pwb_remington_870"] = true,
    ["weapon_pwb_cz75"] = false,
    ["weapon_pwb_desert_eagle"] = false,
    ["qwb_m3super"] = true,
    ["weapon_pwb_fnp45"] = false,
    ["weapon_sib_m249"] = true,
    ["weapon_pwb_m590a1"] = true,
    ["weapon_pwb_rpk"] =true,
    ["weapon_pwb_glock17"] = true,
    ["weapon_pwb_hk23e"] = true,
    ["weapon_pwb_hk416"] = true,
    ["weapon_pwb_l96a1"] = true,
    ["weapon_pwb_hk417"] = true,
    ["weapon_pwb_m320"] = true,
    ["weapon_pwb_pkm"] = true,
    ["weapon_pwb_m134"] = true,
    ["weapon_pwb_tmp"] = true,
    ["weapon_pwb_mp5"] = true,
    ["weapon_pwb_m249"] = true,
    ["weapon_pwb_protecta"] = true,
    ["weapon_pwb_saiga_12"] = true ,
    ["weapon_pwb_uzi"] = false,
    ["weapon_pwb_xm1014"] = true,
    ["weapon_pwb_p99"] = true,
    ["weapon_pwb_m200"] = true,
    ["weapon_pwb_m9"] = true,
    ["weapon_pwb_spas_12"] = true,
    ["weapon_pwb_mp7"] = true,
    ["weapon_sib_m14"] = true,
    ["qwb_usp"] = true,
    ["qwb_ump45"] = true,
    ["weapon_pwb_tar21"] = true,
    }
    
    Automatic = {
    ["qwb_glock18"] = false,
    ["qwb_m3super"] = false,
    ["weapon_pwb_m98b"] = true,
    ["weapon_pwb_xm1014"] = false,
    ["weapon_pwb_spas_12"] = true,
    ["weapon_pwb2_vectorsmg"] = true,
    ["weapon_pwb_tmp"] = true,
    ["weapon_pwb_rpk"] = true,
    ["qwb_ump45"] = true,
    ["weapon_pwb_pkm"] = true,
    ["weapon_pwb_protecta"] = false,
    ["weapon_sib_glock"] = false,
    ["weapon_pwb_l85a1"] = true,
    ["qwb_awp"] = false,
    ["qwb_m3super"] = false,
    ["weapon_pwb_p90"] = true,
    ["weapon_pwb_tar21"] = true,
    ["weapon_sib_beretta"] = false,
    ["weapon_pwb_remington_870"] = false,
    ["weapon_sib_usp"] = false,
    ["weapon_pwb_p99"] = false,
    ["weapon_pwb_akm"] = true,
    ["weapon_sib_m249"] = true,
    ["weapon_pwb_mp5"] = true,
    ["weapon_pwb_mp7"] = true,
    ["weapon_pwb_aks74u"] = true,
    ["weapon_pwb_cz75"] = false,
    ["weapon_pwb_desert_eagle"] = false,
    ["weapon_sib_deagle"] = false,
    ["weapon_pwb_uzi"] = true,
    ["weapon_pwb_fnp45"] = false,
    ["weapon_pwb_glock17"] = false,
    ["weapon_sib_m14"] = true,
    ["weapon_pwb_hk23e"] = true,
    ["weapon_pwb_l96a1"] = true,
    ["weapon_pwb_hk417"] = true,
    ["weapon_pwb_m590a1"] = false,
    ["weapon_pwb_m9"] = false,
    ["weapon_pwb_m249"] = true,
    ["weapon_pwb_hk416"] = true,
    ["weapon_pwb_saiga_12"] = true,
    ["weapon_pwb_m134"] = true,
    ["weapon_pwb_m200"] = true,
    ["weapon_pwb_m320"] = true,
    ["qwb_usp"] = false,
    }
    
  